<?php

namespace GlobalViewBundle\Repository;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSubCategories(){

        $qb = $this->createQueryBuilder('s');
        $qb->select('s')
            ->orderBy('s.nom_fr', 'ASC');

        $query = $qb->getQuery();

        return $query->getResult();

    }
}
